//! Score calibration shared between the benchmark and the site.
//!
//! The raw candidate score is a *ranking* key, not a probability — measured
//! systematically overconfident (ECE 0.185; see `target/eval/methodology.md`).
//! `evaluate` fits an isotonic (monotone) score→probability map on the DEV
//! split only, validates it on the untouched holdout (ECE 0.195→0.013), and
//! persists it here so the site's novel-word pipeline can read every proposal
//! as *P(matches an official decision)*.
//!
//! The file is regenerated by every `evaluate` run — refit whenever the ladder
//! changes — and committed, so the static site build stays self-contained and
//! deterministic.

use serde::{Deserialize, Serialize};
use std::path::Path;

/// Committed location of the fitted calibrator.
pub const PATH: &str = "data/score-calibration.json";

/// Novel-word bucket thresholds on the calibrated probability. The measured
/// precision/recall AT these cutoffs is persisted in [`Calibration`] by every
/// `evaluate` run, so downstream displays never go stale.
pub const PROPOSE_T: f64 = 0.6;
pub const REVIEW_T: f64 = 0.3;

/// A monotone decile map: `deciles[i]` is the calibrated P(normalized match)
/// for raw scores in `[i/10, (i+1)/10)`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Calibration {
    /// What the map was fitted on (provenance, informational).
    pub fitted_on: String,
    /// Holdout ECE of the fitted map (informational, from the fitting run).
    pub holdout_ece: f64,
    /// Measured on the holdout split at [`PROPOSE_T`]: (precision, recall).
    pub propose_pr: (f64, f64),
    /// Measured on the holdout split at [`REVIEW_T`]: (precision, recall).
    pub review_pr: (f64, f64),
    pub deciles: [f64; 10],
}

impl Calibration {
    pub fn load(path: &Path) -> Option<Self> {
        let raw = std::fs::read_to_string(path).ok()?;
        serde_json::from_str(&raw).ok()
    }

    /// Calibrated probability for a raw candidate score.
    pub fn probability(&self, score: f32) -> f64 {
        let b = ((score.clamp(0.0, 1.0) * 10.0) as usize).min(9);
        self.deciles[b]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn probability_maps_by_decile() {
        let c = Calibration {
            fitted_on: String::new(),
            holdout_ece: 0.0,
            propose_pr: (0.0, 0.0),
            review_pr: (0.0, 0.0),
            deciles: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
        };
        assert_eq!(c.probability(0.05), 0.0);
        assert_eq!(c.probability(0.55), 0.5);
        // Scores of exactly 1.0 clamp into the top decile.
        assert_eq!(c.probability(1.0), 0.9);
    }
}
