//! Score calibration shared between the benchmark and the site.
//!
//! The raw candidate score is a *ranking* key, not a probability — measured
//! systematically overconfident (ECE 0.185; see `reports/methodology.md`).
//! `evaluate` fits an isotonic (monotone) score→probability map on the DEV
//! split only, validates it on the untouched holdout (ECE 0.195→0.013), and
//! persists it for consumers of that same official-row pipeline score as
//! *P(matches an official decision)*. It must not be applied to the corpus
//! path's separate cognate-coverage score (issue #89 J26/J27).
//!
//! The file is regenerated by every `evaluate` run — refit whenever the ladder
//! changes — and committed, so compatible static builds stay deterministic.

use serde::{Deserialize, Serialize};
use std::path::Path;

/// Committed location of the fitted calibrator.
pub const PATH: &str = "data/score-calibration.json";
/// Committed location of the corpus-coverage calibrator (V11 item 5 /
/// issue #90), fitted by `corpus-eval --fit` and only READ by `export`.
pub const CORPUS_CALIBRATION_PATH: &str = "data/corpus-calibration.json";
/// V12 item 4: the corpus calibrator is BANDED — a single decile map
/// saturated (every proposal at 0.428) because one coverage score cannot
/// separate a 9-language set from a 4-language one. New domain string so an
/// old flat-map consumer rejects the banded file instead of misreading it.
pub const CORPUS_BANDED_DOMAIN: &str = "corpus-coverage-banded-v2";

/// Attesting-language bands for the corpus calibrator.
pub const LANGS_BANDS: &[&str] = &["2-3", "4-6", "7+"];

pub fn langs_band(n_langs: usize) -> &'static str {
    match n_langs {
        0..=3 => "2-3",
        4..=6 => "4-6",
        _ => "7+",
    }
}

/// One band's fitted decile map plus its own holdout diagnostics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BandFit {
    pub deciles: [f64; 10],
    pub dev_n: usize,
    pub holdout_n: usize,
    pub holdout_ece: f64,
}

/// The banded corpus-coverage calibrator (V12 item 4).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorpusCalibration {
    pub score_domain: String,
    pub fitted_on: String,
    /// Pooled holdout ECE across bands.
    pub holdout_ece: f64,
    /// Holdout precision/recall at the propose/review thresholds, pooled.
    pub propose_pr: (f64, f64),
    pub review_pr: (f64, f64),
    pub bands: std::collections::BTreeMap<String, BandFit>,
}

impl CorpusCalibration {
    pub fn load_for_domain(path: &Path, expected_domain: &str) -> anyhow::Result<Option<Self>> {
        if !path.exists() {
            return Ok(None);
        }
        let raw = std::fs::read_to_string(path)?;
        let cal: Self = serde_json::from_str(&raw)
            .map_err(|e| anyhow::anyhow!("parse corpus calibration {}: {e}", path.display()))?;
        anyhow::ensure!(
            cal.score_domain == expected_domain,
            "corpus calibration {} has score domain {:?}, expected {:?}",
            path.display(),
            cal.score_domain,
            expected_domain
        );
        anyhow::ensure!(
            !cal.bands.is_empty(),
            "corpus calibration {} has no bands",
            path.display()
        );
        Ok(Some(cal))
    }

    /// Calibrated P(reproduces an official decision) for a coverage score in
    /// a given attesting-language band.
    pub fn probability(&self, score: f32, n_langs: usize) -> f64 {
        let band = langs_band(n_langs);
        let fit = self
            .bands
            .get(band)
            .or_else(|| self.bands.values().next())
            .expect("corpus calibration has at least one band");
        fit.deciles[((score.clamp(0.0, 1.0) * 10.0) as usize).min(9)]
    }
}

/// Per-decile Wilson-95 lower bounds pooled monotone by PAVA — the banded
/// fit's per-band recipe. The Wilson bound shrinks thin deciles toward 0
/// (a thinly-observed bucket ships a conservative probability), and the
/// clamp keeps every shipped value a proper open-interval probability.
pub fn fit_wilson_isotonic_deciles(samples: &[(f32, bool)]) -> [f64; 10] {
    let mut bins = [(0usize, 0usize); 10];
    for (score, hit) in samples {
        let b = ((score.clamp(0.0, 1.0) * 10.0) as usize).min(9);
        bins[b].0 += 1;
        bins[b].1 += *hit as usize;
    }
    let mut pools: Vec<(f64, f64)> = Vec::new();
    for (n, hits) in &bins {
        if *n == 0 {
            continue;
        }
        pools.push((*n as f64, crate::derive::wilson_lower(*hits, *n)));
        while pools.len() >= 2 && pools[pools.len() - 2].1 > pools[pools.len() - 1].1 {
            let (w2, m2) = pools.pop().expect("len >= 2 loop guard");
            let (w1, m1) = pools.pop().expect("len >= 2 loop guard");
            pools.push((w1 + w2, (w1 * m1 + w2 * m2) / (w1 + w2)));
        }
    }
    let mut iso = [0.0f64; 10];
    let mut pi = 0usize;
    let mut left = pools.first().map_or(0.0, |p| p.0);
    for (b, (n, _)) in bins.iter().enumerate() {
        if *n == 0 {
            iso[b] = pools.get(pi).map_or(0.0, |p| p.1);
            continue;
        }
        iso[b] = pools[pi].1;
        left -= *n as f64;
        if left <= 0.0 && pi + 1 < pools.len() {
            pi += 1;
            left = pools[pi].0;
        }
    }
    for v in iso.iter_mut() {
        *v = v.clamp(0.005, 0.995);
    }
    iso
}
/// Score semantics accepted by the official-row pipeline calibrator.
pub const PIPELINE_SCORE_DOMAIN: &str = "pipeline-candidate-score-v1";

/// Novel-word bucket thresholds on the calibrated probability. The measured
/// precision/recall AT these cutoffs is persisted in [`Calibration`] by every
/// `evaluate` run, so downstream displays never go stale.
pub const PROPOSE_T: f64 = 0.6;
pub const REVIEW_T: f64 = 0.3;

/// A monotone decile map: `deciles[i]` is the calibrated P(normalized match)
/// for raw scores in `[i/10, (i+1)/10)`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Calibration {
    /// Machine-checked semantics of the input score.
    pub score_domain: String,
    /// What the map was fitted on (human-readable provenance).
    pub fitted_on: String,
    /// Holdout ECE of the fitted map (informational, from the fitting run).
    pub holdout_ece: f64,
    /// Measured on the holdout split at [`PROPOSE_T`]: (precision, recall).
    pub propose_pr: (f64, f64),
    /// Measured on the holdout split at [`REVIEW_T`]: (precision, recall).
    pub review_pr: (f64, f64),
    pub deciles: [f64; 10],
}

/// Decile-histogram isotonic fit (pool-adjacent-violators), the same recipe
/// `evaluate` applies inline for the pipeline calibrator (kept separate there
/// to leave the benchmark path byte-stable; a future refactor can unify).
/// `samples` are (score, hit) pairs from the DEV split only.
pub fn fit_isotonic_deciles(samples: &[(f32, bool)]) -> [f64; 10] {
    let mut bins = [(0usize, 0usize); 10]; // (n, hits) per score decile
    for (score, hit) in samples {
        let b = ((score.clamp(0.0, 1.0) * 10.0) as usize).min(9);
        bins[b].0 += 1;
        bins[b].1 += *hit as usize;
    }
    let mut pools: Vec<(f64, f64)> = Vec::new(); // (weight, mean)
    for (n, hits) in &bins {
        if *n == 0 {
            continue;
        }
        pools.push((*n as f64, *hits as f64 / *n as f64));
        while pools.len() >= 2 && pools[pools.len() - 2].1 > pools[pools.len() - 1].1 {
            let (w2, m2) = pools.pop().expect("len >= 2 loop guard");
            let (w1, m1) = pools.pop().expect("len >= 2 loop guard");
            pools.push((w1 + w2, (w1 * m1 + w2 * m2) / (w1 + w2)));
        }
    }
    let mut iso = [0.0f64; 10];
    let mut pi = 0usize;
    let mut left = pools.first().map_or(0.0, |p| p.0);
    for (b, (n, _)) in bins.iter().enumerate() {
        if *n == 0 {
            iso[b] = pools.get(pi).map_or(0.0, |p| p.1);
            continue;
        }
        iso[b] = pools[pi].1;
        left -= *n as f64;
        if left <= 0.0 && pi + 1 < pools.len() {
            pi += 1;
            left = pools[pi].0;
        }
    }
    iso
}

/// (ECE, Brier) of `samples` under an optional decile map (None = raw score
/// as probability). Shared by fit-time holdout validation.
pub fn ece_brier(samples: &[(f32, bool)], deciles: Option<&[f64; 10]>) -> (f64, f64) {
    let mut b10 = [(0usize, 0.0f64, 0usize); 10];
    let mut brier = 0.0f64;
    for (score, hit) in samples {
        let p = match deciles {
            Some(d) => d[((score.clamp(0.0, 1.0) * 10.0) as usize).min(9)],
            None => score.clamp(0.0, 1.0) as f64,
        };
        let y = *hit as u8 as f64;
        brier += (p - y) * (p - y);
        let b = ((p * 10.0) as usize).min(9);
        b10[b].0 += 1;
        b10[b].1 += p;
        b10[b].2 += *hit as usize;
    }
    let n = samples.len().max(1) as f64;
    let mut ece = 0.0f64;
    for (bn, sp, hits) in &b10 {
        if *bn == 0 {
            continue;
        }
        ece += (*bn as f64 / n) * (sp / *bn as f64 - *hits as f64 / *bn as f64).abs();
    }
    (ece, brier / n)
}

impl Calibration {
    /// `Ok(None)` when the file doesn't exist; a file that exists but doesn't
    /// parse is a hard error, not a silent fallback.
    pub fn load(path: &Path) -> anyhow::Result<Option<Self>> {
        if !path.exists() {
            return Ok(None);
        }
        let raw = std::fs::read_to_string(path)?;
        Ok(Some(serde_json::from_str(&raw).map_err(|e| {
            anyhow::anyhow!("parse calibration {}: {e}", path.display())
        })?))
    }

    /// Load only a calibrator fitted for `expected_domain`. Applying a map to
    /// another score domain is a hard error: both values may lie in 0–1 while
    /// representing unrelated ranking functions.
    pub fn load_for_domain(path: &Path, expected_domain: &str) -> anyhow::Result<Option<Self>> {
        let Some(cal) = Self::load(path)? else {
            return Ok(None);
        };
        anyhow::ensure!(
            cal.score_domain == expected_domain,
            "calibration {} has score domain {:?}, expected {:?}",
            path.display(),
            cal.score_domain,
            expected_domain
        );
        Ok(Some(cal))
    }

    /// Calibrated probability for a raw candidate score.
    pub fn probability(&self, score: f32) -> f64 {
        let b = ((score.clamp(0.0, 1.0) * 10.0) as usize).min(9);
        self.deciles[b]
    }

    /// Band-exclusive precision of the review band p ∈ [REVIEW_T, PROPOSE_T)
    /// — the Medium badge's own population. `review_pr` is
    /// threshold-INCLUSIVE (all p ≥ 0.3, so it also counts the High band and
    /// overstates the band rate). Derived from the two persisted operating
    /// points: with H = total holdout matches, hits_t = recall_t·H and
    /// n_t = hits_t/precision_t, so band precision =
    /// (r₁−r₂) / (r₁/p₁ − r₂/p₂), H cancelling. `None` when the derived
    /// band is empty or degenerate.
    pub fn review_band_precision(&self) -> Option<f64> {
        let (p_prec, p_rec) = self.propose_pr;
        let (r_prec, r_rec) = self.review_pr;
        if p_prec <= 0.0 || r_prec <= 0.0 {
            return None;
        }
        let band_hits = r_rec - p_rec;
        let band_n = r_rec / r_prec - p_rec / p_prec;
        if band_n <= 0.0 || band_hits < 0.0 {
            return None;
        }
        Some(band_hits / band_n)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_a_calibrator_from_another_score_domain() {
        let path = std::env::temp_dir().join(format!(
            "slovowiki-calibration-domain-{}.json",
            std::process::id()
        ));
        let c = Calibration {
            score_domain: PIPELINE_SCORE_DOMAIN.to_string(),
            fitted_on: String::new(),
            holdout_ece: 0.0,
            propose_pr: (0.0, 0.0),
            review_pr: (0.0, 0.0),
            deciles: [0.0; 10],
        };
        std::fs::write(&path, serde_json::to_string(&c).unwrap()).unwrap();
        assert!(Calibration::load_for_domain(&path, PIPELINE_SCORE_DOMAIN)
            .unwrap()
            .is_some());
        let err = Calibration::load_for_domain(&path, "some-other-domain-v9")
            .unwrap_err()
            .to_string();
        assert!(err.contains("score domain"), "{err}");
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn probability_maps_by_decile() {
        let c = Calibration {
            score_domain: PIPELINE_SCORE_DOMAIN.to_string(),
            fitted_on: String::new(),
            holdout_ece: 0.0,
            propose_pr: (0.0, 0.0),
            review_pr: (0.0, 0.0),
            deciles: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
        };
        assert_eq!(c.probability(0.05), 0.0);
        assert_eq!(c.probability(0.55), 0.5);
        // Scores of exactly 1.0 clamp into the top decile.
        assert_eq!(c.probability(1.0), 0.9);
    }

    /// The Medium badge's band-exclusive precision derived from the two
    /// COMMITTED operating points (data/score-calibration.json as of this
    /// commit): propose (0.71615, 0.66348), review (0.61657, 0.88866)
    /// → ≈0.437, NOT review_pr's threshold-inclusive 0.617 (issue #77
    /// review finding 2). Pinned to ±0.01 of 0.439.
    #[test]
    fn review_band_precision_is_band_exclusive() {
        let c = Calibration {
            score_domain: PIPELINE_SCORE_DOMAIN.to_string(),
            fitted_on: String::new(),
            holdout_ece: 0.0,
            propose_pr: (0.7161500815660685, 0.6634760705289673),
            review_pr: (0.6165676336945124, 0.8886649874055416),
            deciles: [0.0; 10],
        };
        let band = c.review_band_precision().expect("band exists");
        assert!((band - 0.439).abs() < 0.01, "band precision {band}");
        // Degenerate operating points yield None, never a bogus rate.
        let degenerate = Calibration {
            propose_pr: (0.0, 0.0),
            review_pr: (0.0, 0.0),
            ..c
        };
        assert_eq!(degenerate.review_band_precision(), None);
    }

    /// The display re-bucket (issue #77: `from_probability ∘ probability`)
    /// must span Low→High on the committed calibrator's decile shape: the
    /// flat floor (0.136, scores < 0.4) lands under REVIEW_T and the cap
    /// (0.733, scores ≥ 0.8) clears PROPOSE_T.
    #[test]
    fn display_rebucket_spans_low_to_high_on_committed_deciles() {
        use crate::model::Confidence;
        let c = Calibration {
            score_domain: PIPELINE_SCORE_DOMAIN.to_string(),
            fitted_on: String::new(),
            holdout_ece: 0.0,
            propose_pr: (0.0, 0.0),
            review_pr: (0.0, 0.0),
            deciles: [
                0.136, 0.136, 0.136, 0.136, 0.193, 0.397, 0.593, 0.660, 0.733, 0.733,
            ],
        };
        assert_eq!(
            Confidence::from_probability(c.probability(0.2)),
            Confidence::Low
        );
        assert_eq!(
            Confidence::from_probability(c.probability(0.99)),
            Confidence::High
        );
    }
}
